
  document.querySelectorAll('.faq-item').forEach(item=>{
    item.querySelector('.faq-q').addEventListener('click',()=>{
      const isOpen = item.classList.contains('open');
      document.querySelectorAll('.faq-item').forEach(i=>i.classList.remove('open'));
      if(!isOpen) item.classList.add('open');
    });
  });

  const compradores = [
  { nome: 'Ana', cidade: 'Petrópolis' },
  { nome: 'João', cidade: 'Rio de Janeiro' },
  { nome: 'Mariana', cidade: 'São Paulo' },
  { nome: 'Lucas', cidade: 'Belo Horizonte' },
  { nome: 'Fernanda', cidade: 'Curitiba' },
  { nome: 'Rafael', cidade: 'Brasília' },
  { nome: 'Camila', cidade: 'Niterói' },
  { nome: 'Gustavo', cidade: 'Campinas' },
  { nome: 'Patrícia', cidade: 'Recife' },
  { nome: 'Thiago', cidade: 'Fortaleza' },
  { nome: 'Juliana', cidade: 'Salvador' },
  { nome: 'Felipe', cidade: 'Vitória' },
  { nome: 'Larissa', cidade: 'Manaus' },
  { nome: 'Bruno', cidade: 'Belém' },
  { nome: 'Aline', cidade: 'Porto Alegre' },
  { nome: 'Diego', cidade: 'Florianópolis' },
  { nome: 'Beatriz', cidade: 'Goiânia' },
  { nome: 'Henrique', cidade: 'Cuiabá' },
  { nome: 'Natália', cidade: 'Campo Grande' },
  { nome: 'Vinícius', cidade: 'Maceió' },
  { nome: 'Isabela', cidade: 'João Pessoa' },
  { nome: 'Eduardo', cidade: 'Natal' },
  { nome: 'Renata', cidade: 'Aracaju' },
  { nome: 'Marcelo', cidade: 'Teresina' },
  { nome: 'Paula', cidade: 'São Luís' },
  { nome: 'Leonardo', cidade: 'Palmas' },
  { nome: 'Carolina', cidade: 'Porto Velho' },
  { nome: 'André', cidade: 'Boa Vista' },
  { nome: 'Tatiane', cidade: 'Macapá' },
  { nome: 'Rodrigo', cidade: 'Rio Branco' },
  { nome: 'Sabrina', cidade: 'Santos' },
  { nome: 'Caio', cidade: 'Sorocaba' },
  { nome: 'Priscila', cidade: 'Ribeirão Preto' },
  { nome: 'Igor', cidade: 'São José dos Campos' },
  { nome: 'Vanessa', cidade: 'Taubaté' },
  { nome: 'Daniel', cidade: 'Volta Redonda' },
  { nome: 'Michele', cidade: 'Nova Iguaçu' },
  { nome: 'Fábio', cidade: 'Duque de Caxias' },
  { nome: 'Bianca', cidade: 'São Gonçalo' },
  { nome: 'Márcio', cidade: 'Caxias do Sul' },
  { nome: 'Débora', cidade: 'Londrina' },
  { nome: 'Ricardo', cidade: 'Maringá' },
  { nome: 'Elaine', cidade: 'Joinville' },
  { nome: 'Alexandre', cidade: 'Blumenau' },
  { nome: 'Cristiane', cidade: 'Chapecó' },
  { nome: 'Murilo', cidade: 'Pelotas' },
  { nome: 'Jéssica', cidade: 'Santa Maria' },
  { nome: 'Roberto', cidade: 'Uberlândia' },
  { nome: 'Amanda', cidade: 'Juiz de Fora' },
  { nome: 'César', cidade: 'Montes Claros' },
  { nome: 'Lívia', cidade: 'Ipatinga' },
  { nome: 'Otávio', cidade: 'Contagem' },
  { nome: 'Yasmin', cidade: 'Betim' },
  { nome: 'Samuel', cidade: 'Anápolis' },
  { nome: 'Gabriela', cidade: 'Aparecida de Goiânia' },
  { nome: 'Matheus', cidade: 'Vila Velha' },
  { nome: 'Cláudia', cidade: 'Serra' },
  { nome: 'Wesley', cidade: 'Cariacica' },
  { nome: 'Monique', cidade: 'Juazeiro do Norte' },
  { nome: 'Leandro', cidade: 'Petrolina' },
  { nome: 'Karla', cidade: 'Feira de Santana' },
  { nome: 'Tiago', cidade: 'Ilhéus' },
  { nome: 'Raquel', cidade: 'Vitória da Conquista' },
  { nome: 'Hugo', cidade: 'Cascavel' },
  { nome: 'Simone', cidade: 'Foz do Iguaçu' },
  { nome: 'Douglas', cidade: 'Ponta Grossa' },
  { nome: 'Viviane', cidade: 'Guarulhos' },
  { nome: 'Alan', cidade: 'Osasco' },
  { nome: 'Mônica', cidade: 'Santo André' },
  { nome: 'Ruan', cidade: 'São Bernardo do Campo' },
  { nome: 'Helena', cidade: 'Diadema' },
  { nome: 'Pedro', cidade: 'Jundiaí' },
  { nome: 'Luana', cidade: 'Piracicaba' },
  { nome: 'Guilherme', cidade: 'Bauru' },
  { nome: 'Tatiana', cidade: 'Franca' },
  { nome: 'Erick', cidade: 'Araraquara' },
  { nome: 'Flávia', cidade: 'São Carlos' },
  { nome: 'Rogério', cidade: 'Presidente Prudente' },
  { nome: 'Nicolas', cidade: 'Barueri' },
  { nome: 'Alessandra', cidade: 'Mogi das Cruzes' },
  { nome: 'Pablo', cidade: 'Itaboraí' },
  { nome: 'Cintia', cidade: 'Petrópolis' },
  { nome: 'Jean', cidade: 'Teresópolis' },
  { nome: 'Bruna', cidade: 'Nova Friburgo' },
  { nome: 'Vitor', cidade: 'Resende' },
  { nome: 'Kelly', cidade: 'Barra Mansa' },
  { nome: 'Renan', cidade: 'Angra dos Reis' },
  { nome: 'Luciana', cidade: 'Cabo Frio' },
  { nome: 'Filipe', cidade: 'Macaé' },
  { nome: 'Ariane', cidade: 'Campos dos Goytacazes' },
  { nome: 'Danilo', cidade: 'Maricá' },
  { nome: 'Estela', cidade: 'Araruama' },
  { nome: 'Victor', cidade: 'Saquarema' },
  { nome: 'Silvia', cidade: 'Itaguaí' },
  { nome: 'Emanuel', cidade: 'Queimados' },
  { nome: 'Lorena', cidade: 'Mesquita' },
  { nome: 'Breno', cidade: 'Nilópolis' },
  { nome: 'Dayane', cidade: 'Belford Roxo' },
  { nome: 'Jonas', cidade: 'Magé' },
  { nome: 'Adriana', cidade: 'Arapiraca' },
  { nome: 'Cauã', cidade: 'Ji-Paraná' },
  { nome: 'Davi', cidade: 'Angra dos Reis' },
  { nome: 'Ester', cidade: 'Rondonópolis' },
  { nome: 'Fabiana', cidade: 'Parauapebas' },
  { nome: 'Geovana', cidade: 'Castanhal' },
  { nome: 'Heitor', cidade: 'Santana' },
  { nome: 'Iara', cidade: 'Lages' },
  { nome: 'Jaqueline', cidade: 'Criciúma' },
  { nome: 'Kaique', cidade: 'Itajaí' },
  { nome: 'Luan', cidade: 'Balneário Camboriú' },
  { nome: 'Melissa', cidade: 'Jaraguá do Sul' },
  { nome: 'Noemi', cidade: 'Rio do Sul' },
  { nome: 'Orlando', cidade: 'Passo Fundo' },
  { nome: 'Pamela', cidade: 'Novo Hamburgo' },
  { nome: 'Quésia', cidade: 'São Leopoldo' },
  { nome: 'Rita', cidade: 'Canoas' },
  { nome: 'Sérgio', cidade: 'Uruguaiana' },
  { nome: 'Talita', cidade: 'Bagé' },
  { nome: 'Ulisses', cidade: 'Rio Grande' },
  { nome: 'Valéria', cidade: 'Santa Cruz do Sul' },
  { nome: 'William', cidade: 'Erechim' },
  { nome: 'Xênia', cidade: 'Ijuí' },
  { nome: 'Yuri', cidade: 'Toledo' },
  { nome: 'Zilda', cidade: 'Paranavaí' },
  { nome: 'Adriano', cidade: 'Umuarama' },
  { nome: 'Bárbara', cidade: 'Apucarana' },
  { nome: 'Clóvis', cidade: 'Avaré' },
  { nome: 'Denise', cidade: 'Botucatu' },
  { nome: 'Elisa', cidade: 'Catanduva' },
  { nome: 'Fernando', cidade: 'Limeira' },
  { nome: 'Graziela', cidade: 'Americana' },
  { nome: 'Hélio', cidade: 'Indaiatuba' },
  { nome: 'Ingrid', cidade: 'Hortolândia' },
  { nome: 'Joana', cidade: 'Sumaré' },
  { nome: 'Kevin', cidade: 'Paulínia' },
  { nome: 'Lara', cidade: 'Atibaia' },
  { nome: 'Mário', cidade: 'Bragança Paulista' },
  { nome: 'Neide', cidade: 'Itu' },
  { nome: 'Olívia', cidade: 'Salto' },
  { nome: 'Paulo', cidade: 'Itapetininga' },
  { nome: 'Rafaela', cidade: 'Registro' },
  { nome: 'Saulo', cidade: 'Caraguatatuba' },
  { nome: 'Teresa', cidade: 'Ubatuba' },
  { nome: 'Ursula', cidade: 'Ilhabela' },
  { nome: 'Vera', cidade: 'Pindamonhangaba' },
  { nome: 'Wagner', cidade: 'Lorena' },
  { nome: 'Xavier', cidade: 'Cruzeiro' },
  { nome: 'Yara', cidade: 'Guaratinguetá' },
  { nome: 'Zaqueu', cidade: 'Mococa' },
  { nome: 'Afonso', cidade: 'Votuporanga' },
  { nome: 'Bia', cidade: 'Fernandópolis' },
  { nome: 'Cecília', cidade: 'Jales' },
  { nome: 'Darlan', cidade: 'Ourinhos' },
  { nome: 'Eloá', cidade: 'Assis' },
  { nome: 'Fátima', cidade: 'Marília' },
  { nome: 'Gilberto', cidade: 'Tupã' },
  { nome: 'Hanna', cidade: 'Araçatuba' },
  { nome: 'Ivan', cidade: 'Birigui' },
  { nome: 'Janaína', cidade: 'Lins' },
  { nome: 'Kátia', cidade: 'Penápolis' },
  { nome: 'Lúcio', cidade: 'Andradina' },
  { nome: 'Mirela', cidade: 'Dracena' },
  { nome: 'Natan', cidade: 'Adamantina' },
  { nome: 'Ornela', cidade: 'Bebedouro' },
  { nome: 'Pietra', cidade: 'Barretos' },
  { nome: 'Quintino', cidade: 'Olímpia' },
  { nome: 'Raimundo', cidade: 'Jaboticabal' },
  { nome: 'Selma', cidade: 'Monte Alto' },
  { nome: 'Túlio', cidade: 'Taquaritinga' },
  { nome: 'Ubirajara', cidade: 'Sertãozinho' },
  { nome: 'Verônica', cidade: 'Batatais' },
  { nome: 'Wallace', cidade: 'Cravinhos' },
  { nome: 'Ximena', cidade: 'Serrana' },
  { nome: 'Ygor', cidade: 'Altinópolis' },
  { nome: 'Zenaide', cidade: 'Ibitinga' },
  { nome: 'Alda', cidade: 'Matão' },
  { nome: 'Benício', cidade: 'Jaguariúna' },
  { nome: 'Cora', cidade: 'Valinhos' },
  { nome: 'Dante', cidade: 'Vinhedo' },
  { nome: 'Emanuelle', cidade: 'Amparo' },
  { nome: 'Fabrício', cidade: 'Mogi Guaçu' },
  { nome: 'Gisele', cidade: 'Mogi Mirim' },
  { nome: 'Haroldo', cidade: 'Poços de Caldas' },
  { nome: 'Ítalo', cidade: 'Pouso Alegre' },
  { nome: 'Júlio', cidade: 'Varginha' },
  { nome: 'Karen', cidade: 'Lavras' },
  { nome: 'Lídia', cidade: 'Itajubá' },
  { nome: 'Marlon', cidade: 'Passos' },
  { nome: 'Nina', cidade: 'Patos de Minas' },
  { nome: 'Osvaldo', cidade: 'Patrocínio' },
  { nome: 'Poliana', cidade: 'Araxá' },
  { nome: 'Quitéria', cidade: 'Paracatu' },
  { nome: 'Rosana', cidade: 'Unaí' },
  { nome: 'Tadeu', cidade: 'Teófilo Otoni' },
  { nome: 'Uriel', cidade: 'Governador Valadares' },
  { nome: 'Valdemar', cidade: 'Coronel Fabriciano' },
  { nome: 'Wellington', cidade: 'Timóteo' },
  { nome: 'Xisto', cidade: 'Diamantina' },
  { nome: 'Yasmine', cidade: 'Ouro Preto' },
  { nome: 'Zuleica', cidade: 'Mariana' }
];

const popup = document.getElementById('popup-compra');
const nomeEl = document.getElementById('popup-nome');
const textoEl = document.getElementById('popup-texto');

function mostrarPopup(){
  const pessoa = compradores[Math.floor(Math.random()*compradores.length)];

  nomeEl.textContent = pessoa.nome;
  textoEl.textContent = `de ${pessoa.cidade} acabou de comprar este produto`;

  popup.classList.add('show');

  setTimeout(()=>{
    popup.classList.remove('show');
  },4000);
}

// primeiro popup após 4s
setTimeout(mostrarPopup,4000);

// repete a cada 10s
setInterval(mostrarPopup,10000);